DATA_FOLDER_PATH = "../../DATA/"
REAL_DATA_FOLDER_PATH = DATA_FOLDER_PATH + f'/TINS/'
SYNTHETIC_DATA_FOLDER_PATH = DATA_FOLDER_PATH + f'/SIMULATIONS/'
DIR_RESULTS = "./results/"
DIR_FIGURES = "./figures/"
