LABEL_COLOR_MAP = {-1: 'gray',
                   0: 'red',
                   1: 'lightblue',
                   2: 'green',
                   3: 'yellow',
                   4: 'magenta',
                   5: 'cyan',
                   6: 'wheat',
                   7: 'yellowgreen',
                   8: 'orchid',
                   9: 'tab:orange',
                   10: 'tab:brown',
                   11: 'tab:pink',
                   12: 'lime',
                   13: 'silver',
                   14: 'khaki',
                   15: 'lightgreen',
                   16: 'orangered',
                   17: 'salmon',
                   18: 'tab:purple',
                   19: 'turquoise',
                   20: 'royalblue',
                   21: 'beige',
                   22: 'crimson',
                   23: 'indigo',
                   24: 'darkblue',
                   25: 'gold',
                   26: 'ivory',
                   27: 'lavender',
                   28: 'lightblue',
                   29: 'olive',
                   30: 'sienna',
                   31: 'salmon',
                   32: 'turquoise',
                   }


LABEL_COLOR_MAP2 = {-1: 'gray',
                   0: 'white',
                   1: 'red',
                   2: 'mediumblue',
                   3: 'green',
                   4: 'yellow',
                   5: 'magenta',
                   6: 'cyan',
                   7: 'wheat',
                   8: 'yellowgreen',
                   9: 'orchid',
                   10: 'tab:orange',
                   11: 'tab:brown',
                   12: 'tab:pink',
                   13: 'lime',
                   14: 'silver',
                   15: 'khaki',
                   16: 'lightgreen',
                   17: 'orangered',
                   18: 'salmon',
                   19: 'tab:purple',
                   20: 'turquoise',
                   21: 'royalblue',
                   22: 'beige',
                   23: 'crimson',
                   24: 'indigo',
                   25: 'darkblue',
                   26: 'gold',
                   27: 'ivory',
                   28: 'lavender',
                   29: 'lightblue',
                   30: 'olive',
                   31: 'sienna',
                   32: 'salmon',
                   33: 'turquoise',
                   }


LABEL_COLOR_MAP_SMALLER = {
    0: 'lightskyblue',     # blue 1
    1: 'deepskyblue',      # blue 2
    2: 'dodgerblue',       # blue 3

    3: 'lightgreen',       # green 1
    4: 'mediumseagreen',   # green 2
    5: 'seagreen',         # green 3

    6: 'lightcoral',       # red group
    7: 'coral',
    8: 'darksalmon',
    9: 'salmon',
    10: 'lightsalmon',
    11: 'tomato',
    12: 'indianred',
    13: 'firebrick',
    14: 'brown',
    15: 'maroon',
    16: 'wheat'
}